#!/bin/bash

echo `date` config-changed >> /tmp/charm.log

list-units --format yaml | while read line; do
    unit=`echo $line | cut -d : -f1 | cut -d / -f2`
    echo $unit >> /tmp/charm.log
    [ -f /tmp/rqlite-$unit ] || run-container $unit "rqlited -http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 /rqlite/file/data" FOO=bar rqlite/rqlite
    #"-http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 /rqlite/file/data" "FOO=BAR BAZ=BAT" "rqlite/rqlite"
    echo $unit >> /tmp/rqlite-$unit
done

status-set active "units started"
