#!/bin/bash

echo `date` config-changed >> /tmp/charm.log

list-units --format yaml | while read line; do
    unit=`echo $line | cut -d : -f1 | cut -d / -f2`
    echo $unit >> /tmp/charm.log
    [ -f /tmp/rqlite-$unit ] || run-container $unit "" "" "rqlite/rqlite"
    echo $unit >> /tmp/rqlite-$unit
done

status-set active "units started"
